[project]
name = "zhipu2langchain"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "dotenv>=0.9.9",
    "langchain>=0.3.23",
    "zhipuai>=2.1.5.20250410",
]
